# Generated by Django 3.0.5 on 2020-05-04 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='music',
            new_name='Artist',
        ),
    ]
